Repository automatic-ripping-machine/automatic-ripping-machine, pull requests merged in 2023-02, with the labels that each got.

#693 Security bugfixes and codesmells
  Dockerfile
  arm/ui/auth/auth.py
  arm/ui/jobs/jobs.py
  arm/ui/routes.py
  arm/ui/utils.py
  devtools/armdevtools.py
  devtools/database.py
Labels: bug, Security

#697 Key Update Hotfix
  VERSION
  arm/ripper/makemkv.py
  scripts/update_key.sh
Labels: v2_devel, Docker, Fixed, Ubuntu 20

#709 Fix old links on readme
  README.md
Labels: bug, v2_devel, v2_master

#713 Hotfix for workflow
  .github/workflows/publish-image.yml
Labels: github_actions

#712 Installer removal
  scripts/installers/debian-install.sh
  scripts/installers/docker-setup.sh
  scripts/installers/gentoo-setup-openrc.sh
  scripts/ubuntu-20.04-install.sh
  scripts/ubuntu-quicksync.sh
Labels: enhancement

#723 Fixes #722 - Adds raw folder to installer
  scripts/ubuntu-20.04-install.sh
Labels: Ubuntu 20

#732 Workflow hotfixes
  .github/workflows/publish-image.yml
  .github/workflows/test-pr-image-build.yml
Labels: Fixed

#725 Fixes #625 - arm using HandBrake for Blurays
  arm/ripper/arm_ripper.py
Labels: bug, Python

#734 workflow hotfix
  .github/workflows/publish-image.yml
Labels: Fixed

#739 Add transcode folder
  scripts/docker/runit/arm_user_files_setup.sh
Labels: bug, Docker

#740 Remove warning for NVME drives
  arm/ripper/utils.py
Labels: bug

#742 Fixes #741 - poster image not used from api
  arm/ripper/identify.py
Labels: bug

#744 Add arm to the render group
  scripts/docker/runit/arm_user_files_setup.sh
Labels: bug, Docker

#738 Workflow hotfix
  .github/workflows/test-pr-image-build.yml
Labels: Fixed, github_actions

#751 Updates to MakeMKV key handling and extras
  .github/pull_request_template.md
  .github/workflows/installer_test.yml
  .github/workflows/main.yml
  .github/workflows/publish-image.yml
  .github/workflows/shellcheck.yml
  .github/workflows/test-pr-image-build.yml
  .github/workflows/version_bump.yml
  Dockerfile
  README.md
  arm/config/config.py
  arm/config/config_utils.py
  arm/ripper/makemkv.py
  arm/ui/comments.json
  arm/ui/utils.py
  scripts/docker-setup.sh
  scripts/docker/runit/arm_user_files_setup.sh
  scripts/update_key.sh
  setup/arm.yaml
Labels: enhancement, Docker

#766 Fix bump version github action
  .github/workflows/version_bump.yml
  VERSION
Labels: github_actions

#770 Add more drive support
  Dockerfile
  VERSION
Labels: enhancement

#757 Fixes #728 - Transcode failing for backup mode
  VERSION
  arm/ripper/arm_ripper.py
Labels: Python, Bugfix

#756 Fixes #606 - Error in final move when file extension set
  VERSION
  arm/ripper/handbrake.py
Labels: Bugfix

#743 Raise HandBrake output errors
  VERSION
  arm/ripper/handbrake.py
Labels: Bugfix

#764 Bugfix for #701 and #702
  arm/ripper/main.py
  arm/ripper/utils.py
  arm/ui/json_api.py
  arm/ui/routes.py
  arm/ui/settings/DriveUtils.py
  arm/ui/settings/ServerUtil.py
  arm/ui/settings/settings.py
  arm/ui/settings/templates/settings/sysinfo.html
  arm/ui/templates/index.html
  arm/ui/utils.py
Labels: Bugfix
