Repository automatic-ripping-machine/automatic-ripping-machine, pull requests merged in 2023-07, with the labels that each got.

#891 887 nonetype object has no attribute password UI error
  VERSION
  arm/models/models.py
Labels: bug, Python, arm64

#885 648 notifications from docker link to 127001
  VERSION
  arm/runui.py
Labels: Python, Bugfix

#884 Fixes 838 title matching too aggressive
  VERSION
  arm/ripper/identify.py
Labels: Python, Bugfix

#819 Pr flask sqlalchemy 3 support
  VERSION
  arm/ui/database/database.py
  arm/ui/history/history.py
  arm/ui/utils.py
Labels: dependencies, submodules

#893 753 show hw transcoding support in UI
  VERSION
  arm/ui/settings/settings.py
  arm/ui/settings/templates/settings/sysinfo.html
Labels: enhancement

#894 Enable saving apprise config via armUI
  VERSION
  arm/ui/settings/settings.py
  arm/ui/settings/templates/settings/apprise.html
  arm/ui/utils.py
Labels: enhancement, Feature Added

#895 Update Base Image
  Dockerfile
  VERSION
Labels: dependencies

#886 783 rip longest title
  VERSION
  arm/ripper/makemkv.py
Labels: enhancement

#899 898 stats is undefined on bare metal homepage
  VERSION
  arm/ui/database/database.py
  arm/ui/history/history.py
  arm/ui/routes.py
  arm/ui/settings/settings.py
Labels: Bugfix
