Repository automatic-ripping-machine/automatic-ripping-machine, pull requests merged in 2023-01, with the labels that each got.

#551 System Information and Drive Details into database for status and user edit
  .gitignore
  arm/migrations/README
  arm/migrations/versions/95623e8c5d58_merge_add_notification_and_create_sys_.py
  arm/migrations/versions/9cae4aa05dd7_create_settingsui_table.py
  arm/migrations/versions/c54d68996895_.py
  arm/migrations/versions/edce886fb30f_create_system_table.py
  arm/migrations/versions/version
  arm/models/__init__.py
  arm/models/models.py
  arm/ripper/apprise_bulk.py
  arm/ripper/arm_ripper.py
  arm/ripper/handbrake.py
  arm/ripper/main.py
  arm/ripper/utils.py
  arm/runui.py
  arm/ui/comments.json
  arm/ui/forms.py
  arm/ui/routes.py
  arm/ui/serverutil.py
  arm/ui/static/css/job_details.css
  arm/ui/static/img/drive-optical_closed.svg
  arm/ui/static/img/drive-optical_open.svg
  arm/ui/static/js/common.js
  arm/ui/templates/index.html
  arm/ui/templates/nav.html
  arm/ui/templates/pagination.html
  arm/ui/templates/settings.html
  arm/ui/templates/settings/abcde.html
  arm/ui/templates/settings/apprise.html
  arm/ui/templates/settings/drives.html
  arm/ui/templates/settings/general.html
  arm/ui/templates/settings/help.html
  arm/ui/templates/settings/ripper.html
  arm/ui/templates/settings/sysinfo.html
  arm/ui/templates/settings/tab_sysinfo.html
  arm/ui/templates/settings/ui.html
  arm/ui/templates/support/base_simple.html
  arm/ui/templates/support/databaseupdate.html
  arm/ui/templates/systeminfo.html
  arm/ui/utils.py
  devtools/README.md
  devtools/armdevtools.py
  devtools/armui.py
  devtools/database.py
  devtools/log.py
  docs/PSDs/icons_ripping.psd
  requirements.txt
  scripts/thickclient/arm_wrapper.sh
  setup/30-arm.conf
  setup/armui.service
Labels: bug, enhancement

#655 2.6.9 Hotfixes
  scripts/installers/ubuntu-20.04-install.sh
Labels: Fixed

#657 Fixes breaking change from 2.6.9
  VERSION
  scripts/thickclient/arm_wrapper.sh
Labels: Fixed

#660 Installer Hotfixes
  VERSION
  scripts/installers/ubuntu-20.04-install.sh
Labels: Fixed

#669 Fix Docker breakages caused by 2.6.9+
  Dockerfile
  scripts/docker/runit/arm_user_files_setup.sh
Labels: Docker, Fixed

#680 More Script Fixes
  scripts/docker/runit/arm_user_files_setup.sh
  scripts/installers/ubuntu-20.04-install.sh
Labels: Docker, Fixed, Ubuntu 20

#685 Ubuntu installer fixes
  scripts/installers/ubuntu-20.04-install.sh
Labels: Fixed, Ubuntu 20

#686 ARMUI split out of routes into blueprints
  arm/migrations/versions/6dfe7244b18e_.py
  arm/migrations/versions/95623e8c5d58_merge_add_notification_and_create_sys_.py
  arm/migrations/versions/edce886fb30f_create_system_table.py
  arm/ui/__init__.py
  arm/ui/auth/__init__.py
  arm/ui/auth/auth.py
  arm/ui/auth/templates/login.html
  arm/ui/auth/templates/update_password.html
  arm/ui/database/__init__.py
  arm/ui/database/database.py
  arm/ui/database/templates/databaseview.html
  arm/ui/database/templates/support/base_simple.html
  arm/ui/database/templates/support/databaseupdate.html
  arm/ui/database/templates/test.html
  arm/ui/history/__init__.py
  arm/ui/history/history.py
  arm/ui/history/templates/history.html
  arm/ui/jobs/__init__.py
  arm/ui/jobs/jobs.py
  arm/ui/jobs/templates/activerips.html
  arm/ui/jobs/templates/changeparams.html
  arm/ui/jobs/templates/customTitle.html
  arm/ui/jobs/templates/jobdetail.html
  arm/ui/jobs/templates/list_titles.html
  arm/ui/jobs/templates/showtitle.html
  arm/ui/jobs/templates/titlesearch.html
  arm/ui/logs/__init__.py
  arm/ui/logs/logs.py
  arm/ui/logs/templates/logfiles.html
  arm/ui/logs/templates/logview.html
  arm/ui/routes.py
  arm/ui/sendmovies/__intit__.py
  arm/ui/sendmovies/sendmovies.py
  arm/ui/sendmovies/templates/send_movies.html
  arm/ui/sendmovies/templates/send_movies_form.html
  arm/ui/settings/ServerUtil.py
  arm/ui/settings/__init__.py
  arm/ui/settings/settings.py
  devtools/armdevtools.py
  devtools/armui.py
  devtools/qacheck.py
Labels: enhancement
